from PyQt5.QtWidgets import*
import sys
from PyQt5.QtGui import*



class windows(QWidget):
    def __init__ (self):
        QWidget.__init__(self)
        self.setWindowTitle('سیستم مدیریت شرکت خدماتی')
        
        self.gridlayout = QGridLayout()
        self.setLayout(self.gridlayout)
        self.label_1 =QLabel('Data:')
        self.label_2 =QLabel('1399/3/19')
        self.label_3 =QLabel(' ')
        self.label_4 =QLabel(' ')
        self.label_5 =QLabel(' ')
        self.label_6 =QLabel('In the name of god')
        self.label_7 =QLabel(' ')
        self.label_8 =QLabel(' ')
        self.label_9 =QLabel(' ')
        self.label_10 =QLabel(' ')
        self.label_11 =QLabel('Services required by the company:')
        self.label_12 =QLabel('Services available:')
        self.label_13 =QLabel('1')
        self.label_14 =QLabel('2')
        self.label_15 =QLabel('3')
        self.label_16 =QLabel(' ')
        self.label_17 =QLabel('Group name:')
        self.label_18 =QLabel('...')
        self.label_19 =QLabel(' ')
        self.label_20 =QLabel('1')
        self.label_21 =QLabel('2')
        self.label_22 =QLabel('3')
        self.label_23 =QLabel(' ')
        self.label_24 =QLabel('4')
        self.label_25 =QLabel('5')
        self.label_26 =QLabel('6')
        self.label_27 =QLabel(' ')
        self.label_28 =QLabel('Project Name:')
        self.label_29 =QLabel('...')
        self.label_30 =QLabel(' ')
        self.label_31 =QLabel('4')
        self.label_32 =QLabel('5')
        self.label_33 =QLabel('6')
        self.label_34 =QLabel(' ')
        self.label_35 =QLabel('7')
        self.label_36 =QLabel('8')
        self.label_37 =QLabel('9')
        self.label_38 =QLabel(' ')
        self.label_39 =QLabel(' ')
        self.label_40 =QLabel(' ')
        self.label_41 =QLabel(' ')
        self.label_42 =QLabel('8')
        self.label_43 =QLabel('7')
        self.label_44 =QLabel('9')
        self.label_45 =QLabel(' ')
        self.label_46 =QLabel(' ')
        self.label_47 =QLabel(' ')
        self.label_48 =QLabel(' ')
        self.label_49 =QLabel('Register')
        self.label_50 =QLabel(' ')
        self.label_51 =QLabel(' ')
        self.label_52 =QLabel('Completion of cooperation')
        self.label_53 =QLabel(' ')
        self.label_54 =QLabel(' ')
        self.label_55 =QLabel(' ')
        self.label_56 =QLabel('5,0')
        self.label_57 =QLabel('5,1')
        self.label_58 =QLabel('5,2')
        self.label_59 =QLabel('5,3')
        self.label_60 =QLabel('5,4')
        self.label_61 =QLabel('5,5')
        self.label_62 =QLabel('5,6')
        self.label_63 =QLabel('5,7')
        self.label_64 =QLabel('5,8')
        self.label_65 =QLabel('5,9')
        self.label_66 =QLabel('Search for subscription code')
        self.label_67 =QLabel('6,0')
        self.label_68 =QLabel('6,1')
        self.label_69 =QLabel('6,2')
        self.label_70 =QLabel('6,3')
        self.label_71 =QLabel('6,4')
        self.label_72 =QLabel('6,5')
        self.label_73 =QLabel('6,6')
        self.label_74 =QLabel('6,7')
        self.label_75 =QLabel('6,8')
        self.label_76 =QLabel('6,9')
        self.label_77 =QLabel('6,10')
        self.label_78 =QLabel('7,0')
        self.label_79 =QLabel('7,1')
        self.label_80 =QLabel('7,2')
        self.label_81 =QLabel('7,3')
        self.label_82 =QLabel('7,4')
        self.label_83 =QLabel('7,5')
        self.label_84 =QLabel('7,6')
        self.label_85 =QLabel('7,7')
        self.label_86 =QLabel('7,8')
        self.label_87 =QLabel('7,9')
        self.label_88 =QLabel('Corona News')
        self.label_89 =QLabel('8,0')
        self.label_90 =QLabel('8,1')
        self.label_91 =QLabel('8,2')
        self.label_92 =QLabel('8,3')
        self.label_93 =QLabel('8,4')
        self.label_94 =QLabel('8,5')
        self.label_95 =QLabel('8,6')
        self.label_96 =QLabel('8,7')
        self.label_97 =QLabel('8,8')
        self.label_98 =QLabel('8,9')
        self.label_99 =QLabel('8,10')
        self.label_100 =QLabel('9,0')
        self.label_101 =QLabel('9,1')
        self.label_102 =QLabel('9,2')
        self.label_103 =QLabel('9,3')
        self.label_104 =QLabel('9,4')
        self.label_105 =QLabel('9,5')
        self.label_106 =QLabel('9,6')
        self.label_107 =QLabel('9,7')
        self.label_108 =QLabel('9,8')
        self.label_109 =QLabel('9,9')
        self.label_110 =QLabel('weather')
        self.label_111 =QLabel('10,0')
        self.label_112 =QLabel('10,1')
        self.label_113 =QLabel('10,2')
        self.label_114 =QLabel('10,3')
        self.label_115 =QLabel('10,4')
        self.label_116 =QLabel('10,5')
        self.label_117 =QLabel('10,6')
        self.label_118 =QLabel('10,7')
        self.label_119 =QLabel('10,8')
        self.label_120 =QLabel('10,9')
        self.label_121 =QLabel('...')
        self.gridlayout.addWidget(self.label_1,0,0)
        self.gridlayout.addWidget(self.label_2,0,1)
        self.gridlayout.addWidget(self.label_3,0,2)
        self.gridlayout.addWidget(self.label_4,0,3)
        self.gridlayout.addWidget(self.label_5,0,4)
        self.gridlayout.addWidget(self.label_6,0,5)
        self.gridlayout.addWidget(self.label_7,0,6)
        self.gridlayout.addWidget(self.label_8,0,7)
        self.gridlayout.addWidget(self.label_9,0,8)
        self.gridlayout.addWidget(self.label_10,0,9)
        self.gridlayout.addWidget(self.label_11,0,10)
        self.gridlayout.addWidget(self.label_12,1,0)
        self.gridlayout.addWidget(self.label_13,1,1)
        self.gridlayout.addWidget(self.label_14,1,2)
        self.gridlayout.addWidget(self.label_15,1,3)
        self.gridlayout.addWidget(self.label_16,1,4)
        self.gridlayout.addWidget(self.label_17,1,5)
        self.gridlayout.addWidget(self.label_18,1,6)
        self.gridlayout.addWidget(self.label_19,1,7)
        self.gridlayout.addWidget(self.label_20,1,8)
        self.gridlayout.addWidget(self.label_21,1,9)
        self.gridlayout.addWidget(self.label_22,1,10)
        self.gridlayout.addWidget(self.label_23,2,0)
        self.gridlayout.addWidget(self.label_24,2,1)
        self.gridlayout.addWidget(self.label_25,2,2)
        self.gridlayout.addWidget(self.label_26,2,3)
        self.gridlayout.addWidget(self.label_27,2,4)
        self.gridlayout.addWidget(self.label_28,2,5)
        self.gridlayout.addWidget(self.label_29,2,6)
        self.gridlayout.addWidget(self.label_30,2,7)
        self.gridlayout.addWidget(self.label_31,2,8)
        self.gridlayout.addWidget(self.label_32,2,9)
        self.gridlayout.addWidget(self.label_33,2,10)
        self.gridlayout.addWidget(self.label_34,3,0)
        self.gridlayout.addWidget(self.label_35,3,1)
        self.gridlayout.addWidget(self.label_36,3,2)
        self.gridlayout.addWidget(self.label_37,3,3)
        self.gridlayout.addWidget(self.label_38,3,4)
        self.gridlayout.addWidget(self.label_39,3,5)
        self.gridlayout.addWidget(self.label_40,3,6)
        self.gridlayout.addWidget(self.label_41,3,7)
        self.gridlayout.addWidget(self.label_42,3,8)
        self.gridlayout.addWidget(self.label_43,3,9)
        self.gridlayout.addWidget(self.label_44,3,10)
        self.gridlayout.addWidget(self.label_45,4,0)
        self.gridlayout.addWidget(self.label_46,4,1)
        self.gridlayout.addWidget(self.label_47,4,2)
        self.gridlayout.addWidget(self.label_48,4,3)
        self.gridlayout.addWidget(self.label_49,4,4)
        self.gridlayout.addWidget(self.label_50,4,5)
        self.gridlayout.addWidget(self.label_51,4,6)
        self.gridlayout.addWidget(self.label_52,4,7)
        self.gridlayout.addWidget(self.label_53,4,8)
        self.gridlayout.addWidget(self.label_54,4,9)
        self.gridlayout.addWidget(self.label_55,4,10)
        self.gridlayout.addWidget(self.label_56,5,0)
        self.gridlayout.addWidget(self.label_57,5,1)
        self.gridlayout.addWidget(self.label_58,5,2)
        self.gridlayout.addWidget(self.label_59,5,3)
        self.gridlayout.addWidget(self.label_60,5,4)
        self.gridlayout.addWidget(self.label_61,5,5)
        self.gridlayout.addWidget(self.label_62,5,6)
        self.gridlayout.addWidget(self.label_63,5,7)
        self.gridlayout.addWidget(self.label_64,5,8)
        self.gridlayout.addWidget(self.label_65,5,9)
        self.gridlayout.addWidget(self.label_66,5,10)
        self.gridlayout.addWidget(self.label_67,6,0)
        self.gridlayout.addWidget(self.label_68,6,1)
        self.gridlayout.addWidget(self.label_69,6,2)
        self.gridlayout.addWidget(self.label_70,6,3)
        self.gridlayout.addWidget(self.label_71,6,4)
        self.gridlayout.addWidget(self.label_72,6,5)
        self.gridlayout.addWidget(self.label_73,6,6)
        self.gridlayout.addWidget(self.label_74,6,7)
        self.gridlayout.addWidget(self.label_75,6,8)
        self.gridlayout.addWidget(self.label_76,6,9)
        self.gridlayout.addWidget(self.label_77,6,10)
        self.gridlayout.addWidget(self.label_78,7,0)
        self.gridlayout.addWidget(self.label_79,7,1)
        self.gridlayout.addWidget(self.label_80,7,2)
        self.gridlayout.addWidget(self.label_81,7,3)
        self.gridlayout.addWidget(self.label_82,7,4)
        self.gridlayout.addWidget(self.label_83,7,5)
        self.gridlayout.addWidget(self.label_84,7,6)
        self.gridlayout.addWidget(self.label_85,7,7)
        self.gridlayout.addWidget(self.label_86,7,8)
        self.gridlayout.addWidget(self.label_87,7,9)
        self.gridlayout.addWidget(self.label_88,7,10)
        self.gridlayout.addWidget(self.label_89,8,0)
        self.gridlayout.addWidget(self.label_90,8,1)
        self.gridlayout.addWidget(self.label_91,8,2)
        self.gridlayout.addWidget(self.label_92,8,3)
        self.gridlayout.addWidget(self.label_93,8,4)
        self.gridlayout.addWidget(self.label_94,8,5)
        self.gridlayout.addWidget(self.label_95,8,6)
        self.gridlayout.addWidget(self.label_96,8,7)
        self.gridlayout.addWidget(self.label_97,8,8)
        self.gridlayout.addWidget(self.label_98,8,9)
        self.gridlayout.addWidget(self.label_99,8,10)
        self.gridlayout.addWidget(self.label_100,9,0)
        self.gridlayout.addWidget(self.label_101,9,1)
        self.gridlayout.addWidget(self.label_102,9,2)
        self.gridlayout.addWidget(self.label_103,9,3)
        self.gridlayout.addWidget(self.label_104,9,4)
        self.gridlayout.addWidget(self.label_105,9,5)
        self.gridlayout.addWidget(self.label_106,9,6)
        self.gridlayout.addWidget(self.label_107,9,7)
        self.gridlayout.addWidget(self.label_108,9,8)
        self.gridlayout.addWidget(self.label_109,9,9)
        self.gridlayout.addWidget(self.label_110,9,10)
        self.gridlayout.addWidget(self.label_111,10,0)
        self.gridlayout.addWidget(self.label_112,10,1)
        self.gridlayout.addWidget(self.label_113,10,2)
        self.gridlayout.addWidget(self.label_114,10,3)
        self.gridlayout.addWidget(self.label_115,10,4)
        self.gridlayout.addWidget(self.label_116,10,5)
        self.gridlayout.addWidget(self.label_117,10,6)
        self.gridlayout.addWidget(self.label_118,10,7)
        self.gridlayout.addWidget(self.label_119,10,8)
        self.gridlayout.addWidget(self.label_120,10,9)
        self.gridlayout.addWidget(self.label_121,10,10)

      
class Service:
    def __init__ (self,k="None",v="None"):
        self.key = k
        self.value = v

    def Services(self):
        S ={"Selected person : %d , Provider services : %d)" %(self.key , self.value) } 

    def Update(self,nk="mahdi ",nv="Py"):
        self.Newkey = nk
        self.Newvalue = nv
        

print(Service.Services())

App=QApplication(sys.argv)
win= windows()
win.show()
sys.exit(App.exec_())